// Check that Telemetry api is functioning (with default page length of 20)
GET {{host}}:{{port}}/api/satellites/1/telemetry

> {%
    client.test("Telemetry array length check", function () {
        client.assert(response.body.length === 20, "Expected length 20, got " + response.body.length);
    });
%}

###

// Check for latest Telemetry api function
GET {{host}}:{{port}}/api/satellites/1/telemetry/latest

> {%
    client.log("Latest telemetry latitude: " + response.body.latitudeDeg)
%}

###

// Check the Telemetry hub
POST {{host}}:{{port}}/hubs/telemetry/negotiate