// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitalWatch.Api.Data;

#nullable disable

namespace OrbitalWatch.Api.Migrations
{
    [DbContext(typeof(OrbitalWatchDbContext))]
    [Migration("20260613184852_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OrbitalWatch.Api.Models.ConjunctionAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CollisionProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MissDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("PrimarySatelliteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondarySatelliteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOfClosestApproach")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("SecondarySatelliteId");

                    b.HasIndex("PrimarySatelliteId", "IsResolved");

                    b.ToTable("ConjunctionAlerts");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.Maneuver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DeltaVMagnitudeKms")
                        .HasColumnType("REAL");

                    b.Property<double>("DeltaVXKms")
                        .HasColumnType("REAL");

                    b.Property<double>("DeltaVYKms")
                        .HasColumnType("REAL");

                    b.Property<double>("DeltaVZKms")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SatelliteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteId", "PlannedAt");

                    b.ToTable("Maneuvers");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.Satellite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoradId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrbitalRegime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoradId")
                        .IsUnique();

                    b.ToTable("Satellites");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudeDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeDeg")
                        .HasColumnType("REAL");

                    b.Property<int>("SatelliteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpeedKms")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("VelocityXKms")
                        .HasColumnType("REAL");

                    b.Property<double>("VelocityYKms")
                        .HasColumnType("REAL");

                    b.Property<double>("VelocityZKms")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("SatelliteId", "Timestamp");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.ConjunctionAlert", b =>
                {
                    b.HasOne("OrbitalWatch.Api.Models.Satellite", "PrimarySatellite")
                        .WithMany()
                        .HasForeignKey("PrimarySatelliteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitalWatch.Api.Models.Satellite", "SecondarySatellite")
                        .WithMany()
                        .HasForeignKey("SecondarySatelliteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimarySatellite");

                    b.Navigation("SecondarySatellite");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.Maneuver", b =>
                {
                    b.HasOne("OrbitalWatch.Api.Models.Satellite", "Satellite")
                        .WithMany("Maneuvers")
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satellite");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.TelemetryEvent", b =>
                {
                    b.HasOne("OrbitalWatch.Api.Models.Satellite", "Satellite")
                        .WithMany("TelemetryEvents")
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satellite");
                });

            modelBuilder.Entity("OrbitalWatch.Api.Models.Satellite", b =>
                {
                    b.Navigation("Maneuvers");

                    b.Navigation("TelemetryEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
